### ISSUE TITLE
Membuat Implementasi Desain Landing Page Ke Layout XML (Android Code)

### ISSUE THREAD

**Issue by atylestari** [septilsnna/infused-paint#10]

**Comment by atylestari** [comment]
![landing1](https://user-images.githubusercontent.com/56219136/94726992-3e43d300-0388-11eb-9e94-c28caa5de430.JPG)
![landing2](https://user-images.githubusercontent.com/56219136/94727003-41d75a00-0388-11eb-9c26-ce110feaca81.JPG)
![landing3](https://user-images.githubusercontent.com/56219136/94727006-44d24a80-0388-11eb-8332-e1c63c4d2de9.JPG)

**Comment by septilsnna** [comment]
Terdapat error pada activity_landing1.xml saat ingin debug
