### ISSUE TITLE
Membuat Desain Halaman Profile Pada Figma

### ISSUE THREAD

**Issue by apraira** [septilsnna/infused-paint#13]
- [x] Terdapat Avatar User

- [x] Terdapat Nama User

- [x] Terdapat Tombol Edit Profile

- [x] Terdapat About

- [x] Terdapat App Version

**Comment by apraira** [comment]
![image](https://user-images.githubusercontent.com/43996652/94559282-2f2b2b00-028b-11eb-93e2-f6565dd5e8c0.png)

**Comment by atylestari** [comment]
Tambahin feature logoutnya, ra

**Comment by septilsnna** [comment]
Bergabung sejak juga boleh deh kayaknya, sama jumlah gambar yang udah di ubah ke lukisannya

**Comment by apraira** [comment]
@septilsnna @atylestari thank youu reviewnya

**Comment by apraira** [comment]
Need to add:

- [x] Log Out Button

- [x] Join Date

- [x] Number of Picture That have been affected with filter

**Comment by apraira** [comment]
![image](https://user-images.githubusercontent.com/43996652/94648850-9f828c80-031d-11eb-867a-1eda71721fef.png)
https://www.figma.com/file/N0P1dpkODsjC1QDhE2xEXZ/Infused-Paint?node-id=9%3A33
